version: 2.1
jobs:
  deploy:
    docker: 
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: "Install vsce tool."
          command: yarn install --ignore-engines
      - run:
          name: "Deploy to extension marketplace."
          command: yarn deploy -p ${VSCODE_MARKETPLACE_TOKEN}

workflows:
  main:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/